Maps
7/CoronaExchange pull request #33
Opened 2020-03-22 11:35 UTC by kiwikern

zoom level and map center are static

2020-03-22 11:36 UTC, kiwikern commented
I did not commit the rebuilt dist folder

2020-03-22 12:32 UTC, BenjaminKaul approved these changes

2020-03-22 12:32 UTC, merged

2022-12-19 06:01 UTC, o3q3 reviewed
bos3iid7@gmail.com

2022-12-19 06:02 UTC, o3q3 requested changes
Pl

2022-12-19 06:03 UTC, o3q3 reviewed
[saad](Instagram.com/5)

2022-12-19 08:12 UTC, o3q3 reviewed
@7p

2022-12-19 08:12 UTC, o3q3 commented on public/src/main.js
> +Icon.Default.mergeOptions({
bos3iid7@gmail.com

2022-12-19 08:12 UTC, o3q3 commented
thefloyd77@gmail.com